"""A chess model that answers what is true about a position.

Squares, roles, colours and file sets are text here; every side-paired fact is
a pair, indexed by `esca.US` and `esca.THEM`.
"""

from . import lichess, pgn, uci
from ._esca import (
    CHESS960,
    CLASSIC,
    KING_TO_ROOK,
    KING_TWO_SQUARES,
    MOVE_WIDTH,
    SCHEMA,
    SCHEMA_ID,
    SCHEMA_V1,
    THEM,
    US,
    WIDTH,
    AnnotatedMove,
    AttackFacts,
    Facts,
    Game,
    HistoryFacts,
    KingFacts,
    MaterialFacts,
    MobilityFacts,
    Move,
    MoveFacts,
    PawnFacts,
    PieceFacts,
    PlacementFacts,
    PlaneFacts,
    Position,
    Schema,
    SquareSet,
    StateFacts,
    TacticsFacts,
    Variant,
    __version__,
    encode,
    encode_into,
    encode_moves,
    features_for,
    schema,
)

__all__ = [
    "CHESS960",
    "CLASSIC",
    "KING_TO_ROOK",
    "KING_TWO_SQUARES",
    "MOVE_WIDTH",
    "SCHEMA",
    "SCHEMA_ID",
    "SCHEMA_V1",
    "THEM",
    "US",
    "WIDTH",
    "AnnotatedMove",
    "AttackFacts",
    "Facts",
    "Game",
    "HistoryFacts",
    "KingFacts",
    "MaterialFacts",
    "MobilityFacts",
    "Move",
    "MoveFacts",
    "PawnFacts",
    "PieceFacts",
    "PlacementFacts",
    "PlaneFacts",
    "Position",
    "Schema",
    "SquareSet",
    "StateFacts",
    "TacticsFacts",
    "Variant",
    "__version__",
    "encode",
    "encode_into",
    "encode_moves",
    "features_for",
    "lichess",
    "pgn",
    "schema",
    "uci",
]
