"""The compiled extension. Its public names are re-exported by `esca`."""

import os
from collections.abc import Iterator, Sequence
from typing import Final, TypedDict, final, overload

import numpy as np
from numpy.typing import NDArray

__version__: Final[str]

CLASSIC: Final[Variant]
CHESS960: Final[Variant]

US: Final[int]
THEM: Final[int]

KING_TO_ROOK: Final[str]
KING_TWO_SQUARES: Final[str]

SCHEMA_V1: Final[Schema]
SCHEMA: Final[Schema]
SCHEMA_ID: Final[str]
WIDTH: Final[int]
MOVE_WIDTH: Final[int]

class GroupInfo(TypedDict):
    """Where a schema group sits and how wide it is."""

    name: str
    version: int
    width: int
    offset: int

@final
class Variant:
    """One set of chess rules."""

    @staticmethod
    def named(name: str) -> Variant: ...
    @property
    def name(self) -> str: ...
    @property
    def promotion_roles(self) -> list[str]: ...
    def start_position(self, seed: int = 0) -> Position: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class SquareSet:
    """A set of squares, named `e4`-style."""

    def __new__(cls, squares: Sequence[str] | None = None) -> SquareSet: ...
    @property
    def bits(self) -> int: ...
    @property
    def squares(self) -> list[str]: ...
    def is_subset(self, other: SquareSet) -> bool: ...
    def __len__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __contains__(self, square: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def __and__(self, other: SquareSet) -> SquareSet: ...
    def __or__(self, other: SquareSet) -> SquareSet: ...
    def __xor__(self, other: SquareSet) -> SquareSet: ...
    def __sub__(self, other: SquareSet) -> SquareSet: ...
    def __invert__(self) -> SquareSet: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Move:
    """One action: origin, destination, promotion role and kind."""

    def __new__(
        cls,
        origin: str,
        destination: str,
        promotion: str | None = None,
        kind: str = "quiet",
        is_capture: bool = False,
    ) -> Move: ...
    @property
    def origin(self) -> str: ...
    @property
    def destination(self) -> str: ...
    @property
    def promotion(self) -> str | None: ...
    @property
    def kind(self) -> str: ...
    @property
    def is_capture(self) -> bool: ...
    @property
    def is_castling(self) -> bool: ...
    @property
    def is_en_passant(self) -> bool: ...
    @property
    def uci(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Position:
    """Placement and state, with no rules attached."""

    @staticmethod
    def from_fen(fen: str) -> Position: ...
    @property
    def fen(self) -> str: ...
    @property
    def epd(self) -> str: ...
    @property
    def side_to_move(self) -> str: ...
    @property
    def castling_rights(self) -> str: ...
    @property
    def en_passant(self) -> str | None: ...
    @property
    def halfmove_clock(self) -> int: ...
    @property
    def fullmove_number(self) -> int: ...
    @property
    def clocks_known(self) -> bool: ...
    @property
    def in_check(self) -> bool: ...
    @property
    def occupied(self) -> SquareSet: ...
    @property
    def key(self) -> int: ...
    def piece_at(self, square: str) -> str | None: ...
    def by_role(self, role: str) -> SquareSet: ...
    def by_colour(self, colour: str) -> SquareSet: ...
    def by_piece(self, role: str, colour: str) -> SquareSet: ...
    def king_of(self, colour: str) -> str: ...
    def see(self, square: str) -> int: ...
    def see_capture(self, mv: Move) -> int: ...
    def facts(self, variant: Variant | None = None) -> Facts: ...
    def mirrored(self) -> Position: ...
    def summary(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Game:
    """A variant, a start position and the moves played from it."""

    def __new__(cls, *, variant: Variant | None = None, seed: int = 0) -> Game: ...
    @staticmethod
    def from_fen(fen: str, *, variant: Variant | None = None) -> Game: ...
    @staticmethod
    def from_position(position: Position, *, variant: Variant | None = None) -> Game: ...
    @property
    def variant(self) -> Variant: ...
    @property
    def position(self) -> Position: ...
    @property
    def start_position(self) -> Position: ...
    @property
    def moves(self) -> list[Move]: ...
    @property
    def positions(self) -> list[Position]: ...
    @property
    def ply(self) -> int: ...
    @property
    def castling_output(self) -> str: ...
    @castling_output.setter
    def castling_output(self, style: str) -> None: ...
    def legal_moves(self) -> list[Move]: ...
    def annotated_moves(self) -> list[AnnotatedMove]: ...
    def play(self, mv: Move | str) -> None: ...
    def play_san(self, text: str) -> None: ...
    def undo(self) -> Move | None: ...
    def move_to_uci(self, mv: Move) -> str: ...
    def move_to_san(self, mv: Move) -> str: ...
    def outcome(self) -> str | None: ...
    def claims(self) -> list[str]: ...
    def repetitions(self) -> int: ...
    def facts(self) -> Facts: ...
    def to_pgn(self) -> PgnGame: ...

@final
class Schema:
    """The versioned contract between the extractor and the net."""

    @property
    def id(self) -> str: ...
    @property
    def semver(self) -> str: ...
    @property
    def width(self) -> int: ...
    @property
    def feature_count(self) -> int: ...
    @property
    def group_names(self) -> list[str]: ...
    def groups(self) -> list[GroupInfo]: ...
    def width_of(self, groups: Sequence[str] | None = None) -> int: ...
    def features_for(self, variant: Variant) -> list[tuple[str, str]]: ...
    def canonical(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
    def __hash__(self) -> int: ...

@final
class PlacementFacts:
    """Where the units stand: one square set per side and role."""

    @property
    def by_role(self) -> tuple[list[SquareSet], list[SquareSet]]: ...

@final
class StateFacts:
    """Game-state flags."""

    @property
    def in_check(self) -> bool: ...
    @property
    def double_check(self) -> bool: ...
    @property
    def castle_short(self) -> tuple[bool, bool]: ...
    @property
    def castle_long(self) -> tuple[bool, bool]: ...
    @property
    def en_passant(self) -> str | None: ...
    @property
    def ep_capture_legal(self) -> bool: ...

@final
class HistoryFacts:
    """What the plies before this position say."""

    @property
    def known(self) -> bool: ...
    @property
    def halfmove_clock(self) -> int: ...
    @property
    def halfmove_known(self) -> bool: ...
    @property
    def repetition_seen(self) -> bool: ...
    @property
    def repetition_available(self) -> bool: ...
    @property
    def captures_in_last_8(self) -> int: ...
    @property
    def checks_in_last_8(self) -> int: ...
    @property
    def quiet_plies(self) -> int: ...
    @property
    def material_trend(self) -> int: ...
    @property
    def last_move_victim(self) -> str | None: ...
    @property
    def last_move_mover(self) -> str | None: ...

@final
class MaterialFacts:
    """Material and phase."""

    @property
    def count(self) -> tuple[list[int], list[int]]: ...
    @property
    def non_pawn_value(self) -> tuple[int, int]: ...
    @property
    def value(self) -> tuple[int, int]: ...
    @property
    def phase(self) -> float: ...
    @property
    def both_queens(self) -> bool: ...
    @property
    def pawns_only(self) -> bool: ...
    @property
    def insufficient(self) -> tuple[bool, bool]: ...

@final
class PawnFacts:
    """Pawn structure."""

    @property
    def pawns(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def passed(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def candidates(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def doubled(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def isolated(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def backward(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def defended(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def count_by_file(self) -> tuple[list[int], list[int]]: ...
    @property
    def count_by_rank(self) -> tuple[list[int], list[int]]: ...
    @property
    def open_files(self) -> str: ...
    @property
    def semi_open_files(self) -> tuple[str, str]: ...
    @property
    def islands(self) -> tuple[int, int]: ...
    @property
    def levers(self) -> tuple[int, int]: ...
    @property
    def rams(self) -> int: ...
    @property
    def passer_lead_rank(self) -> tuple[int | None, int | None]: ...
    @property
    def passer_protected(self) -> tuple[int, int]: ...
    @property
    def passers_connected(self) -> tuple[bool, bool]: ...
    @property
    def passer_unstoppable(self) -> tuple[bool, bool]: ...
    @property
    def chain_max_length(self) -> tuple[int, int]: ...
    @property
    def chain_base_attacked(self) -> tuple[bool, bool]: ...
    @property
    def majority_by_wing(self) -> tuple[tuple[bool, bool], tuple[bool, bool]]: ...
    @property
    def holes(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def holes_occupied(self) -> tuple[int, int]: ...
    @property
    def fixed_pawns(self) -> tuple[int, int]: ...
    @property
    def blocked_passers(self) -> tuple[int, int]: ...
    @property
    def passer_distance(self) -> tuple[int | None, int | None]: ...
    @property
    def passer_king_distance(
        self,
    ) -> tuple[tuple[int | None, int | None], tuple[int | None, int | None]]: ...
    @property
    def passer_in_square(self) -> tuple[bool, bool]: ...
    @property
    def passer_free_path(self) -> tuple[int, int]: ...
    @property
    def half_open_at_enemy_king(self) -> tuple[int, int]: ...
    @property
    def backward_on_semi_open(self) -> tuple[int, int]: ...

@final
class PieceFacts:
    """Bishops, rooks, knights and queens."""

    @property
    def bishop_pair(self) -> tuple[bool, bool]: ...
    @property
    def bishops_light(self) -> tuple[int, int]: ...
    @property
    def bishops_dark(self) -> tuple[int, int]: ...
    @property
    def opposite_coloured_bishops(self) -> bool: ...
    @property
    def pawns_on_bishop_colour(self) -> tuple[int, int]: ...
    @property
    def rooks_connected_rank(self) -> tuple[bool, bool]: ...
    @property
    def rooks_connected_file(self) -> tuple[bool, bool]: ...
    @property
    def rooks_on_open_file(self) -> tuple[int, int]: ...
    @property
    def rooks_on_semi_open_file(self) -> tuple[int, int]: ...
    @property
    def rooks_on_relative_7th(self) -> tuple[int, int]: ...
    @property
    def rook_behind_own_passer(self) -> tuple[int, int]: ...
    @property
    def rook_behind_enemy_passer(self) -> tuple[int, int]: ...
    @property
    def trapped_rook(self) -> tuple[bool, bool]: ...
    @property
    def outposts(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def minors_on_outpost(self) -> tuple[int, int]: ...
    @property
    def outpost_squares_free(self) -> tuple[int, int]: ...
    @property
    def knights_on_rim(self) -> tuple[int, int]: ...
    @property
    def minors_undeveloped(self) -> tuple[int, int]: ...
    @property
    def queen_developed(self) -> tuple[bool, bool]: ...
    @property
    def fixed_pawns_on_bishop_colour(self) -> tuple[int, int]: ...
    @property
    def bishop_pair_vs_knight_pair(self) -> int: ...
    @property
    def rook_on_7th_with_king_on_8th(self) -> tuple[bool, bool]: ...
    @property
    def trapped_pieces(self) -> tuple[int, int]: ...
    @property
    def trapped_value(self) -> tuple[int, int]: ...

@final
class KingFacts:
    """King safety and shelter."""

    @property
    def square(self) -> tuple[str, str]: ...
    @property
    def on_home_square(self) -> tuple[bool, bool]: ...
    @property
    def castled_queenside(self) -> tuple[bool, bool]: ...
    @property
    def castled_kingside(self) -> tuple[bool, bool]: ...
    @property
    def shield_files(self) -> tuple[str, str]: ...
    @property
    def shield(self) -> tuple[list[int | None], list[int | None]]: ...
    @property
    def file_open(self) -> tuple[list[bool], list[bool]]: ...
    @property
    def file_semi_open_for_enemy(self) -> tuple[list[bool], list[bool]]: ...
    @property
    def storm(self) -> tuple[list[int | None], list[int | None]]: ...
    @property
    def ring(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def ring_attackers(self) -> tuple[int, int]: ...
    @property
    def ring_attack_weight(self) -> tuple[int, int]: ...
    @property
    def ring_defended(self) -> tuple[int, int]: ...
    @property
    def ring_holes(self) -> tuple[int, int]: ...
    @property
    def escape_squares(self) -> tuple[int, int]: ...
    @property
    def back_rank_risk(self) -> tuple[bool, bool]: ...
    @property
    def distance(self) -> int: ...
    @property
    def tropism(self) -> tuple[float, float]: ...
    @property
    def virtual_mobility(self) -> tuple[int, int]: ...
    @property
    def ring_defenders(self) -> tuple[int, int]: ...
    @property
    def ring_defence_weight(self) -> tuple[int, int]: ...
    @property
    def ring_attacker_surplus(self) -> tuple[int, int]: ...
    @property
    def open_rays(self) -> tuple[int, int]: ...
    @property
    def luft(self) -> tuple[bool, bool]: ...
    @property
    def castled_side(self) -> tuple[str | None, str | None]: ...
    @property
    def opposite_side_castling(self) -> bool: ...

@final
class MobilityFacts:
    """Mobility and space."""

    @property
    def by_role(self) -> tuple[list[int], list[int]]: ...
    @property
    def safe_by_role(self) -> tuple[list[int], list[int]]: ...
    @property
    def total(self) -> tuple[int, int]: ...
    @property
    def space(self) -> tuple[int, int]: ...
    @property
    def controlled(self) -> tuple[int, int]: ...
    @property
    def centre_control(self) -> tuple[int, int]: ...
    @property
    def extended_centre_control(self) -> tuple[int, int]: ...
    @property
    def immobile_pieces(self) -> tuple[int, int]: ...

@final
class AttackFacts:
    """The attack maps and what they say about the units on the board."""

    @property
    def by(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def by_pawns(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def by_role(self) -> tuple[list[SquareSet], list[SquareSet]]: ...
    @property
    def attacked(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def hanging(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def en_prise(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def pinned(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def defended(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def attacked_value(self) -> tuple[int, int]: ...
    @property
    def hanging_value(self) -> tuple[int, int]: ...
    @property
    def en_prise_value(self) -> tuple[int, int]: ...
    @property
    def en_prise_max_value(self) -> tuple[int, int]: ...
    @property
    def pinned_value(self) -> tuple[int, int]: ...
    @property
    def skewer_candidates(self) -> tuple[int, int]: ...
    def attackers_of(self, square: str, side: int) -> SquareSet: ...
    def is_hanging(self, square: str) -> bool: ...
    def units(self, side: int) -> SquareSet: ...

@final
class ExchangeFacts:
    """One side's captures, judged by the exchange they start."""

    @property
    def see_best_capture(self) -> int: ...
    @property
    def see_positive_capture_count(self) -> int: ...
    @property
    def see_equal_capture_count(self) -> int: ...
    @property
    def see_positive_total(self) -> int: ...

@final
class ThreatFacts:
    """What each side stands to lose, and the slider geometry behind it."""

    @property
    def threatened(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def threatened_value(self) -> tuple[int, int]: ...
    @property
    def threat_max_gain(self) -> tuple[int, int]: ...
    @property
    def attacked_by_lesser(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def queen_attacked_by_lesser(self) -> tuple[bool, bool]: ...
    @property
    def overloaded_defenders(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def removable_defenders(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def loose(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def attacker_surplus(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def xray_through_enemy(self) -> tuple[int, int]: ...
    @property
    def battery_count(self) -> tuple[int, int]: ...
    @property
    def battery_at_king(self) -> tuple[bool, bool]: ...

@final
class TacticsFacts:
    """One side's one-ply tactical options."""

    @property
    def available(self) -> bool: ...
    @property
    def check_count(self) -> int: ...
    @property
    def check_by_role(self) -> list[bool]: ...
    @property
    def safe_check_count(self) -> int: ...
    @property
    def safe_check_by_role(self) -> list[bool]: ...
    @property
    def double_check_available(self) -> bool: ...
    @property
    def discovered_check_available(self) -> bool: ...
    @property
    def mate_in_1(self) -> bool: ...
    @property
    def stalemate_in_1(self) -> bool: ...
    @property
    def promotion_files(self) -> str: ...
    @property
    def promotion_roles(self) -> list[bool]: ...
    @property
    def safe_promotion_files(self) -> str: ...
    @property
    def capture_count(self) -> int: ...
    @property
    def winning_capture_available(self) -> bool: ...
    @property
    def winning_capture_max_gain(self) -> int: ...
    @property
    def captures_hanging(self) -> bool: ...
    @property
    def hanging_victim_max_value(self) -> int: ...
    @property
    def equal_capture_count(self) -> int: ...
    @property
    def losing_capture_count(self) -> int: ...
    @property
    def fork_count(self) -> int: ...
    @property
    def fork_max_value(self) -> int: ...
    @property
    def knight_fork_available(self) -> bool: ...
    @property
    def royal_fork_available(self) -> bool: ...
    @property
    def pin_creation_count(self) -> int: ...
    @property
    def skewer_creation_available(self) -> bool: ...
    @property
    def discovered_attack_available(self) -> bool: ...
    @property
    def legal_move_count(self) -> int: ...
    @property
    def check_available(self) -> bool: ...
    @property
    def safe_check_available(self) -> bool: ...
    @property
    def promotion_available(self) -> bool: ...
    @property
    def safe_promotion_available(self) -> bool: ...
    @property
    def capture_available(self) -> bool: ...
    @property
    def fork_available(self) -> bool: ...
    @property
    def pin_creation_available(self) -> bool: ...
    @property
    def only_moves(self) -> bool: ...

@final
class EndgameFacts:
    """Where the kings stand, how the pawn race runs, and which drawn
    configuration the material is."""

    @property
    def king_centralisation(self) -> tuple[int, int]: ...
    @property
    def race_plies(self) -> tuple[int, int]: ...
    @property
    def race_plies_diff(self) -> int: ...
    @property
    def opposition(self) -> str | None: ...
    @property
    def key_square_occupied(self) -> tuple[bool, bool]: ...
    @property
    def wrong_colour_bishop(self) -> tuple[bool, bool]: ...
    @property
    def drawish_material(self) -> str | None: ...

@final
class PlaneFacts:
    """The eight square sets the `planes` group emits."""

    @property
    def attacked(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def attacked_by_pawns(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def hanging(self) -> tuple[SquareSet, SquareSet]: ...
    @property
    def pinned(self) -> tuple[SquareSet, SquareSet]: ...

@final
class MoveFacts:
    """What one legal move does, beyond what the move itself says."""

    @property
    def victim(self) -> str | None: ...
    @property
    def mover(self) -> str: ...
    @property
    def promotion(self) -> str | None: ...
    @property
    def gives_check(self) -> bool: ...
    @property
    def gives_safe_check(self) -> bool: ...
    @property
    def is_safe(self) -> bool: ...
    @property
    def captures_hanging(self) -> bool: ...
    @property
    def escapes_attack(self) -> bool: ...
    @property
    def to_attacked_by_pawn(self) -> bool: ...
    @property
    def is_castling(self) -> bool: ...
    @property
    def is_en_passant(self) -> bool: ...
    @property
    def see(self) -> int: ...
    @property
    def threat_created_max(self) -> int: ...
    @property
    def moves_attacked_unit(self) -> bool: ...
    @property
    def blocks_check(self) -> bool: ...
    @property
    def advances_passer(self) -> bool: ...
    @property
    def creates_passer(self) -> bool: ...
    @property
    def creates_isolated(self) -> bool: ...
    @property
    def creates_doubled(self) -> bool: ...
    @property
    def creates_backward(self) -> bool: ...
    @property
    def opens_file_at_enemy_king(self) -> bool: ...
    @property
    def our_ring_attackers_delta(self) -> int: ...
    @property
    def their_ring_attackers_delta(self) -> int: ...
    @property
    def own_hanging_delta(self) -> int: ...
    @property
    def their_hanging_delta(self) -> int: ...
    @property
    def leaves_unit_hanging(self) -> bool: ...
    @property
    def gives_discovered_attack(self) -> bool: ...

@final
class AnnotatedMove:
    """A legal move and its facts."""

    @property
    def move(self) -> Move: ...
    @property
    def facts(self) -> MoveFacts: ...

@final
class Facts:
    """Everything the v1 schema says about one position.

    Pickling re-reads the facts from the position they were computed for, so
    the history flags a game supplies do not survive a round trip.
    """

    def __new__(cls, fen: str, *, variant: Variant | None = None) -> Facts: ...
    @property
    def variant(self) -> Variant: ...
    @property
    def side_to_move(self) -> str: ...
    def side(self, colour: str) -> int: ...
    @property
    def position(self) -> Position: ...
    @property
    def placement(self) -> PlacementFacts: ...
    @property
    def state(self) -> StateFacts: ...
    @property
    def history(self) -> HistoryFacts: ...
    @property
    def material(self) -> MaterialFacts: ...
    @property
    def pawns(self) -> PawnFacts: ...
    @property
    def pieces(self) -> PieceFacts: ...
    @property
    def king(self) -> KingFacts: ...
    @property
    def mobility(self) -> MobilityFacts: ...
    @property
    def attacks(self) -> AttackFacts: ...
    @property
    def exchange(self) -> tuple[ExchangeFacts, ExchangeFacts]: ...
    @property
    def threats(self) -> ThreatFacts: ...
    @property
    def tactics(self) -> tuple[TacticsFacts, TacticsFacts]: ...
    @property
    def endgame(self) -> EndgameFacts: ...
    @property
    def planes(self) -> PlaneFacts: ...
    @property
    def moves(self) -> list[AnnotatedMove]: ...
    def summary(self) -> str: ...

@final
class PgnNode:
    """One move of a game tree."""

    @property
    def move(self) -> Move: ...
    @property
    def san(self) -> str: ...
    @property
    def nags(self) -> list[int]: ...
    @property
    def comment_before(self) -> str: ...
    @property
    def comment_after(self) -> str: ...
    @property
    def variations(self) -> list[list[PgnNode]]: ...

@final
class PgnGame:
    """A game as PGN describes one: tag pairs, a move tree, and a result."""

    def __new__(cls) -> PgnGame: ...
    @staticmethod
    def from_game(game: Game) -> PgnGame: ...
    @property
    def headers(self) -> dict[str, str]: ...
    @property
    def comment(self) -> str: ...
    @comment.setter
    def comment(self, text: str) -> None: ...
    @property
    def result(self) -> str: ...
    @result.setter
    def result(self, marker: str) -> None: ...
    @property
    def variant(self) -> Variant: ...
    @property
    def start_position(self) -> Position: ...
    def set_header(self, name: str, value: str) -> None: ...
    def mainline(self) -> list[PgnNode]: ...
    def game(self) -> Game: ...
    def to_string(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...

@final
class PgnReader:
    """An iterator over the games of a PGN source."""

    def __iter__(self) -> PgnReader: ...
    def __next__(self) -> PgnGame: ...

@final
class Batch:
    """One batch of positions: their text, their features and their targets."""

    @property
    def fens(self) -> list[str]: ...
    @property
    def features(self) -> NDArray[np.float32]: ...
    @property
    def cp(self) -> NDArray[np.float32]: ...
    @property
    def mate(self) -> NDArray[np.float32]: ...
    @property
    def best_moves(self) -> list[Move]: ...
    def __len__(self) -> int: ...

@final
class Batches:
    """An iterator over the batches of an evaluation dump."""

    def __iter__(self) -> Batches: ...
    def __next__(self) -> Batch: ...

def encode(
    fens: Sequence[str],
    *,
    variant: Variant | None = None,
    schema: Schema | None = None,
    groups: Sequence[str] | None = None,
) -> NDArray[np.float32]: ...
def encode_into(
    fens: Sequence[str],
    out: NDArray[np.float32],
    *,
    variant: Variant | None = None,
    schema: Schema | None = None,
    groups: Sequence[str] | None = None,
) -> None: ...
@overload
def encode_moves(
    fens: str,
    *,
    variant: Variant | None = None,
) -> tuple[list[Move], NDArray[np.float32]]: ...
@overload
def encode_moves(
    fens: Sequence[str],
    *,
    variant: Variant | None = None,
) -> tuple[list[list[Move]], NDArray[np.float32], NDArray[np.int64]]: ...
def features_for(variant: Variant, *, schema: Schema | None = None) -> list[tuple[str, str]]: ...
def schema() -> list[GroupInfo]: ...
def pgn_read(
    path: str | os.PathLike[str],
    *,
    skip_errors: bool = False,
) -> PgnReader: ...
def pgn_read_string(text: str, *, skip_errors: bool = False) -> PgnReader: ...
def pgn_count(path: str | os.PathLike[str]) -> int: ...
def batches(
    path: str | os.PathLike[str],
    *,
    batch_size: int = 8192,
    min_depth: int = 0,
    variant: Variant | None = None,
    schema: Schema | None = None,
    groups: Sequence[str] | None = None,
) -> Batches: ...

class UciError(Exception):
    """The base of every error talking to an engine raises."""

class EngineTimeout(UciError):
    """The engine did not say what was awaited in time."""

class EngineDied(UciError):
    """The engine closed its output or exited."""

class ProtocolError(UciError):
    """The engine broke the order of the conversation."""

@final
class Limits:
    """What bounds a search; times are seconds."""

    def __new__(
        cls,
        *,
        depth: int | None = None,
        nodes: int | None = None,
        movetime: float | None = None,
        mate: int | None = None,
        infinite: bool = False,
        ponder: bool = False,
        white_time: float | None = None,
        black_time: float | None = None,
        white_increment: float | None = None,
        black_increment: float | None = None,
        moves_to_go: int | None = None,
        search_moves: Sequence[str] | None = None,
    ) -> Limits: ...
    @property
    def depth(self) -> int | None: ...
    @property
    def nodes(self) -> int | None: ...
    @property
    def movetime(self) -> float | None: ...
    @property
    def mate(self) -> int | None: ...
    @property
    def infinite(self) -> bool: ...
    @property
    def ponder(self) -> bool: ...
    @property
    def white_time(self) -> float | None: ...
    @property
    def black_time(self) -> float | None: ...
    @property
    def white_increment(self) -> float | None: ...
    @property
    def black_increment(self) -> float | None: ...
    @property
    def moves_to_go(self) -> int | None: ...
    @property
    def search_moves(self) -> list[str]: ...

@final
class Option:
    """One option an engine offers, and the domain it declared for it."""

    @property
    def name(self) -> str: ...
    @property
    def type(self) -> str: ...
    @property
    def default(self) -> bool | int | str | None: ...
    @property
    def min(self) -> int | None: ...
    @property
    def max(self) -> int | None: ...
    @property
    def vars(self) -> list[str]: ...

@final
class Info:
    """One `info` line of a search, its moves read against the position searched."""

    @property
    def depth(self) -> int | None: ...
    @property
    def seldepth(self) -> int | None: ...
    @property
    def time(self) -> float | None: ...
    @property
    def nodes(self) -> int | None: ...
    @property
    def nps(self) -> int | None: ...
    @property
    def pv(self) -> list[Move]: ...
    @property
    def multipv(self) -> int | None: ...
    @property
    def cp(self) -> int | None: ...
    @property
    def mate(self) -> int | None: ...
    @property
    def bound(self) -> str | None: ...
    @property
    def wdl(self) -> tuple[int, int, int] | None: ...
    @property
    def currmove(self) -> Move | None: ...
    @property
    def currmovenumber(self) -> int | None: ...
    @property
    def hashfull(self) -> int | None: ...
    @property
    def tbhits(self) -> int | None: ...
    @property
    def sbhits(self) -> int | None: ...
    @property
    def cpuload(self) -> int | None: ...
    @property
    def refutation(self) -> list[Move]: ...
    @property
    def currline(self) -> list[Move]: ...
    @property
    def currline_cpu(self) -> int | None: ...
    @property
    def string(self) -> str | None: ...
    @property
    def unknown(self) -> list[str]: ...

@final
class Answer:
    """An engine's answer to a search."""

    @property
    def best(self) -> Move | None: ...
    @property
    def ponder(self) -> Move | None: ...

@final
class Search:
    """A search in flight: an iterator over its reports."""

    @property
    def done(self) -> bool: ...
    def answer(self) -> Answer: ...
    def stop(self) -> None: ...
    def ponderhit(self) -> None: ...
    def __iter__(self) -> Search: ...
    def __next__(self) -> Info: ...
    def __enter__(self) -> Search: ...
    def __exit__(self, *args: object) -> None: ...

@final
class Engine:
    """A UCI engine process, addressed with blocking calls."""

    def __new__(
        cls,
        command: str | os.PathLike[str],
        args: Sequence[str] = (),
        *,
        cwd: str | os.PathLike[str] | None = None,
        timeout: float = 10.0,
    ) -> Engine: ...
    @property
    def timeout(self) -> float: ...
    @timeout.setter
    def timeout(self, timeout: float) -> None: ...
    @property
    def name(self) -> str | None: ...
    @property
    def author(self) -> str | None: ...
    @property
    def options(self) -> dict[str, Option]: ...
    @property
    def state(self) -> str: ...
    @property
    def is_alive(self) -> bool: ...
    def handshake(self) -> None: ...
    def option(self, name: str) -> Option | None: ...
    def set_option(self, name: str, value: object = None) -> None: ...
    def debug(self, on: bool) -> None: ...
    def new_game(self) -> None: ...
    def is_ready(self) -> None: ...
    def set_position(self, game: Game) -> None: ...
    def go(self, limits: Limits | None = None, *, timeout: float | None = None) -> Search: ...
    def play(self, game: Game, limits: Limits | None = None, *, timeout: float | None = None) -> Answer: ...
    def analyse(
        self,
        game: Game,
        limits: Limits | None = None,
        *,
        multipv: int | None = None,
        timeout: float | None = None,
    ) -> list[Info]: ...
    def stop(self) -> None: ...
    def ponderhit(self) -> None: ...
    def send_line(self, text: str) -> None: ...
    def next_line(self, timeout: float | None = None) -> str | None: ...
    def quit(self) -> int | None: ...
    def kill(self) -> None: ...
    def __enter__(self) -> Engine: ...
    def __exit__(self, *args: object) -> None: ...
